In [1]:
# !pip install geopandas
# !pip install dbfread
# !pip install ace_tools

In [2]:
import geopandas as gpd
import pandas as pd
import os

In [3]:
os.getcwd()

'c:\\Users\\AICT\\Desktop\\PythonProject\\KNPA_TAD\\src'

In [4]:
# Load the shapefile using all components
file_path = "../data/MOCT_link_model_input"
shp_path  = file_path + ".shp"
df_raw    = gpd.read_file(shp_path, encoding="cp949")

# Display the first few rows of the GeoDataFrame
df_raw.head()

#df_raw.to_csv(file_path + '.csv')

,LINK_ID,F_NODE,T_NODE,LANES,ROAD_RANK,ROAD_TYPE,ROAD_NO,ROAD_NAME,ROAD_USE,MULTI_LINK,...,REST_VEH,REST_W,REST_H,C-ITS,LENGTH,UPDATEDATE,REMARK,HIST_TYPE,HISTREMARK,geometry
0,2220045700,2220021000,2220021100,4,101,000,100,占쏙옙占쏙옙占쏙옙占쏙옙1占쏙옙환占쏙옙占쌈듸옙占쏙옙,0,0,...,5,0,0,0,1129.997445,20230717,None,LINK0005,None,"LINESTRING (210769.782 561426.841, 210506.904 ..."
1,2220776100,2220306500,2220306400,3,101,000,400,占쏙옙占쏙옙占쏙옙占쏙옙2占쏙옙환占쏙옙占쌈듸옙占쏙옙,0,0,...,5,0,0,0,86.166824,20231211,None,LINK0001,None,"LINESTRING (229304.171 554874.758, 229362.169 ..."
2,2240899000,2240290400,2240008100,3,101,000,110,占쏙옙2占쏙옙占싸곤옙占쌈듸옙占쏙옙,0,0,...,5,0,0,0,731.161954,20230519,None,None,None,"LINESTRING (179603.862 536939.159, 179606.581 ..."
3,2210002300,2210000900,2210001000,2,101,000,100,占쏙옙占쏙옙占쏙옙占쏙옙1占쏙옙환占쏙옙占쌈듸옙占쏙옙,0,0,...,5,0,0,0,204.175343,20230717,None,LINK0005,None,"LINESTRING (213953.078 553667.257, 213949.35 5..."
4,2250273300,2250094600,2250001000,3,101,000,50,占쏙옙占쏙옙占쏙옙占쌈듸옙占쏙옙,0,0,...,5,0,0,0,614.102108,20230519,None,None,None,"LINESTRING (195397.378 525430.24, 195381.466 5..."

In [5]:
cond_1 = (df_raw['F_NODE'] == '2250094600')
cond_2 = (df_raw['T_NODE'] == '2250094600')

df_raw[cond_1 | cond_2]

df_raw[(df_raw['LINK_ID'] == '2210002300') | (df_raw['LINK_ID'] == '2210002200')]

,LINK_ID,F_NODE,T_NODE,LANES,ROAD_RANK,ROAD_TYPE,ROAD_NO,ROAD_NAME,ROAD_USE,MULTI_LINK,...,REST_VEH,REST_W,REST_H,C-ITS,LENGTH,UPDATEDATE,REMARK,HIST_TYPE,HISTREMARK,geometry
3,2210002300,2210000900,2210001000,2,101,000,100,占쏙옙占쏙옙占쏙옙占쏙옙1占쏙옙환占쏙옙占쌈듸옙占쏙옙,0,0,...,5,0,0,0,204.175343,20230717,None,LINK0005,None,"LINESTRING (213953.078 553667.257, 213949.35 5..."
319,2210002200,2210001000,2210000900,4,101,000,100,占쏙옙占쏙옙占쏙옙占쏙옙1占쏙옙환占쏙옙占쌈듸옙占쏙옙,0,0,...,5,0,0,0,208.500056,20230717,None,LINK0005,None,"LINESTRING (213857.984 553850.663, 213923.694 ..."

In [7]:
# Load the uploaded CSV file
df_raw = pd.DataFrame(df_raw)

# Build edge connections: LINK_ID_1 and LINK_ID_2 where T_NODE of one matches F_NODE of another
df_mrg = pd.merge(
    df_raw[['LINK_ID', 'F_NODE', 'T_NODE']],
    df_raw[['LINK_ID', 'F_NODE', 'T_NODE']],
    left_on='T_NODE', right_on='F_NODE',
    suffixes=('_1', '_2')
)

# Keep only LINK_ID_1 and LINK_ID_2
df_link = df_mrg[['LINK_ID_1', 'LINK_ID_2']]

# Drop duplicates if needed
df_link = df_link.drop_duplicates()


df_link.head()

    LINK_ID_1   LINK_ID_2
0  2220045700  2220045600
1  2220776100  2220776000
2  2240899000  2240018600
3  2210002300  2210002702
4  2210002300  2210002200

In [ ]:
df_link

df_link.to_csv("../data/Siheung_adj.csv", header=False, index=False)

: